import './App.css';

function App() {
  return (
    <div className="App">
      <div className="header-section">
        <div>
          <h1 className="header-title">
            Carfli - Future on Wheels
          </h1>
        </div>
        <div>
          <p className="header-description">
            Carfli offers a unique mobility solution: users can enjoy our platform as a standard ride-hailing service, or choose to invest in autonomous electric vehicles. The profits generated by these vehicles are shared among the individuals who participate in their ownership, creating a collaborative and sustainable transportation ecosystem.
          </p>
          <div className="cta-section">
            <div className="cta-icon">→</div>
            <span className="cta-text">Start your journey</span>
          </div>
        </div>
      </div>
      <div className="banner-container">
        <img 
          src="https://i.ibb.co/NdkhVCQ0/banner.png" 
          alt="Banner" 
          className="banner"
        />
      </div>
    </div>
  );
}

export default App;